language: java
git:
  depth: 3
jdk:
  - oraclejdk8
env:
  - HADOOP_VERSION=2.6.5
  - HADOOP_VERSION=2.7.5
  - HADOOP_VERSION=2.8.3
script: "travis_wait ./gradlew test --stacktrace --info -Ddyno.hadoop.bin.version=${HADOOP_VERSION}"
